### ISSUE TITLE
unable to connect to database

### ISSUE THREAD

**Issue by Meffi42** [junyang/radb#2] opened 2018-04-04 16:14 UTC
After a fresh install of radb, the beers example cannot be started:

[cloudera@quickstart ~]$ /usr/local/bin/python3.6 --version
Python 3.6.5
[cloudera@quickstart ~]$ ls beers.ra 
beers.ra
[cloudera@quickstart ~]$ radb -i beers.ra beers.db
WARNING: unable to read configuration file /home/cloudera/.radb.ini; resorting to system defaults
ERROR: failed to connect to database: No module named '_sqlite3'

I thought sqlite3 would have been bundled with radb.

**Comment by junyang** [comment] 2019-09-18 20:54
Sorry for the long hiatus. Is this still an issue (> a year later)? I just tried a fresh Ubuntu 18.04 box (Google Compute Engine), and can't reproduce the problem. Below is the list of commands I used on the fresh box, which worked:

sudo apt update
sudo apt-get install python3-pip
pip3 install radb
wget https://raw.githubusercontent.com/junyang/radb/master/sample/beers.ra
radb -i beers.ra beers.db

I will close this issue for now unless there are new reports of the problem. Thanks!

**Closed as completed by junyang** 2019-09-18 20:54 UTC

**Comment by remabarca** [comment] 2025-07-31 17:09
Hi, I have been getting the same issue: can not found the radb.ini it seems the installation is fine I have tried doing some cleans installs but the error is persistent.

Do you have any advice Professor, I want to use radb for database classes on ESCOM IPN, 

best regards. Thanks indeed,

Reyna Melara
